[package]
name = "copypatch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
goblin = "0.8.0"
inkwell = { version = "0.4.0", features = ["llvm17-0"] }
libc = "0.2.153"
